import React from "react";
export function getM16Content() {
  return {
    references: ["Charaka Sutra Sthana Ch. 25", "Sushruta Sharira Sthana Ch. 10", "Kashyapa Samhita — Stanya Adhyaya", "Ashtanga Sangraha", "Williams Obstetrics Ch. 36", "DC Dutta Ch. 11"],
    units: [
      { title: "Stanya Utpatti & Pareeksha", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Stanya (breast milk) is an Upadhatu of Rasa Dhatu. This unit covers Stanya Utpatti (lactogenesis), Stanya Lakshana (properties of normal breast milk), and Stanya Pareeksha (tests for milk quality)."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Stanya Utpatti from Rasa Dhatu via Stanya Vaha Srotas"), React.createElement("li", null, "• Shuddha Stanya Lakshana — normal milk properties"), React.createElement("li", null, "• Stanya Pareeksha — water test for milk quality"), React.createElement("li", null, "• Modern: prolactin, oxytocin let-down reflex"))) },
      { title: "Stanya Dushti & Breast Disorders", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Vitiation of breast milk (Stanya Dushti) by Doshas, and breast pathologies. Modern breast disorders including mastitis, abscess, galactocele, and breast engorgement."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Vataja, Pittaja, Kaphaja Stanya Dushti"), React.createElement("li", null, "• Stanya Shodhana (purification of breast milk)"), React.createElement("li", null, "• Stana Vidradhi (breast abscess), Stana Roga"), React.createElement("li", null, "• Modern: mastitis, cracked nipple, engorgement management"))) },
    ],
    orientation: { why: "Stanya Vigyana is unique to Ayurveda — no other medical system has such detailed description of breast milk quality assessment. Understanding Stanya Pareeksha, Stanya Dushti, and galactagogue preparations alongside modern lactation physiology is essential for integrated postnatal care.", examWeight: "Moderate to high-yield. Short notes on Stanya Pareeksha, Stanya Dushti, and Stanya Janana drugs appear regularly. Comparison with modern lactation physiology is a favourite question." },
    definition: {
      ayurveda: `<p><strong>Stanya</strong> is the Upadhatu (secondary tissue) of Rasa Dhatu, formed in the Stanya Vaha Srotas (lactiferous channels). Shuddha Stanya (pure breast milk) is described as white, sweet, unctuous, and when mixed with water, disperses evenly without discoloration.</p><p class="mt-2">Kashyapa dedicates an entire chapter (Stanya Adhyaya) to breast milk — emphasizing that the quality of Stanya directly affects the health and development of the infant.</p>`,
      modern: `<p><strong>Lactation</strong> is the process of milk secretion by the mammary glands. It involves:<br/><strong>Lactogenesis I:</strong> Colostrum production from mid-pregnancy<br/><strong>Lactogenesis II:</strong> Copious milk production 30-40 hours postpartum (triggered by progesterone withdrawal)<br/><strong>Galactopoiesis:</strong> Maintenance of milk production (prolactin + suckling stimulus)</p><p class="mt-2">Human milk contains proteins, fats, lactose, vitamins, minerals, and immunoglobulins (especially IgA).</p>`,
    },
    shlokas: [
      { source: "Sushruta Sutra Sthana 45/13", devanagari: "अविगन्धि अविवर्णं च यत् क्षीरं स्नेहसंयुतम् |\nजले विमिश्रितं सम्यक् तत् स्तन्यं शुद्धमिष्यते ||", transliteration: "avigandhi avivarṇaṃ ca yat kṣīraṃ snehasaṃyutam |\njale vimiśritaṃ samyak tat stanyaṃ śuddhamiṣyate ||", meaning: "Breast milk that is free from abnormal smell (Avigandhi), free from discoloration (Avivarna), unctuous (Sneha Samyukta), and when mixed with water disperses evenly — such Stanya is considered Shuddha (pure).", clinicalNote: "The Stanya Pareeksha (water test) is a simple bedside test: pure milk disperses evenly in water without sinking, floating, or discolouring. This remains a practical way to assess breast milk quality in Ayurvedic clinical practice." },
      { source: "Kashyapa Samhita — Khila Sthana", devanagari: "स्तन्यदोषात् शिशोर्नित्यं रोगा जायन्ति दारुणाः |\nतस्मात् स्तन्यं परीक्ष्यैव पाययेच्च शिशुं बुधः ||", transliteration: "stanyadoṣāt śiśornityaṃ rogā jāyanti dāruṇāḥ |\ntasmāt stanyaṃ parīkṣyaiva pāyayecca śiśuṃ budhaḥ ||", meaning: "From vitiated breast milk (Stanya Dosha), severe diseases arise in the infant. Therefore, a wise physician should first examine the breast milk and only then allow the infant to feed.", clinicalNote: "This emphasizes that maternal health directly impacts neonatal health through breast milk quality — aligning with modern understanding that maternal infections, drugs, and toxins can pass through breast milk." },
      { source: "Charaka Sutra Sthana 25/40", devanagari: "शतावरी विदारीका जीवन्ती मधुयष्टिका |\nस्तन्यजननानि एतानि इति सूत्रे प्रकीर्तितम् ||", transliteration: "śatāvarī vidārīkā jīvantī madhuyaṣṭikā |\nstanyajananāni etāni iti sūtre prakīrtitam ||", meaning: "Shatavari (Asparagus racemosus), Vidarikanda (Pueraria tuberosa), Jivanti (Leptadenia reticulata), and Yashtimadhu (Glycyrrhiza glabra) are the principal Stanyajanana (galactagogue) drugs mentioned in the Sutras.", clinicalNote: "Shatavari is the most widely used Ayurvedic galactagogue. Modern research shows it increases prolactin levels. Shatavari Kalpa (granules with sugar and ghee) is commonly prescribed postpartum for lactation support." },
    ],
    dualCols: [
      { title: "Lactation Physiology", ayurvedaTitle: "Stanya Utpatti", modernTitle: "Modern Lactation", ayurvedaContent: `<p><strong>Stanya Utpatti:</strong> Stanya is formed from Rasa Dhatu (plasma/lymph) and flows through Stanya Vaha Srotas (lactiferous ducts).</p><p class="mt-2"><strong>Factors affecting Stanya:</strong></p><ul class="list-disc pl-4 space-y-1"><li>Rasa Dhatu quality (depends on Ahara and Agni)</li><li>Stanya Vaha Srotas patency</li><li>Vata regulation (Apana and Vyana Vayu)</li><li>Manas (psychological state — stress reduces Stanya)</li></ul>`, modernContent: `<p><strong>Hormonal control:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Prolactin:</strong> primary milk production hormone. Released by anterior pituitary. Suckling stimulus → increased prolactin</li><li><strong>Oxytocin:</strong> milk ejection (let-down reflex). Released by posterior pituitary</li><li><strong>Progesterone withdrawal:</strong> triggers lactogenesis II after placental delivery</li></ul><p class="mt-2"><strong>Breast milk composition:</strong> Foremilk (watery, high lactose) → Hindmilk (fatty, high calories). Colostrum (Day 1-5): rich in IgA, lactoferrin, leukocytes.</p>` },
    ],
    clinicalFeatures: [{ title: "Stanya Dushti — Types and Features", headers: ["Type", "Ayurvedic Features", "Breast Milk Changes", "Modern Correlation"], rows: [["<strong>Vataja</strong>", "Thin, frothy, astringent", "Ruksha (dry), Phena (frothy)", "Insufficient fat content, dehydration"], ["<strong>Pittaja</strong>", "Yellowish, sour, hot", "Peeta (yellow), Amla (sour)", "Mastitis/infection — inflammatory changes"], ["<strong>Kaphaja</strong>", "Thick, sticky, sweet", "Picchila (slimy), Guru (heavy)", "Galactocele, blocked ducts"], ["<strong>Sannipataja</strong>", "Mixed features", "All Dosha signs combined", "Severe mastitis/abscess"]] }],
    investigations: [{ title: "Breast & Lactation Investigations", headers: ["Investigation", "Purpose", "Indication"], rows: [["<strong>Stanya Pareeksha (water test)</strong>", "Assess breast milk quality — Dosha vitiation", "Routine in Ayurvedic postnatal care"], ["<strong>Breast USG</strong>", "Evaluate breast lump, abscess, galactocele", "Palpable lump, suspected abscess"], ["<strong>Milk culture</strong>", "Identify bacterial infection in breast milk", "Recurrent mastitis, suspected sepsis"], ["<strong>Prolactin level</strong>", "Assess hormonal cause of lactation failure", "Inadequate milk production despite proper technique"], ["<strong>Mammography</strong>", "Screen for breast malignancy", "Suspicious lump in lactating woman >35 yrs"]] }],
    management: {
      diagramTitle: "Lactation Problem — Management Algorithm",
      diagramSvg: `<svg viewBox="0 0 800 400" xmlns="http://www.w3.org/2000/svg" class="w-full max-w-3xl"><style>.box{fill:#FFF8E1;stroke:#C8712A;stroke-width:2;rx:10}.box-blue{fill:#E3F2FD;stroke:#42A5F5;stroke-width:2;rx:10}.box-green{fill:#E8F5E9;stroke:#66BB6A;stroke-width:2;rx:10}.box-red{fill:#FFEBEE;stroke:#EF5350;stroke-width:2;rx:10}.label{font-family:'DM Sans',sans-serif;font-size:12px;fill:#333;text-anchor:middle}.label-bold{font-family:'DM Sans',sans-serif;font-size:13px;fill:#333;font-weight:bold;text-anchor:middle}.arrow{stroke:#C8712A;stroke-width:2;fill:none;marker-end:url(#ah16)}.small{font-size:11px}</style><defs><marker id="ah16" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto"><polygon points="0 0,10 3.5,0 7" fill="#C8712A"/></marker></defs><rect class="box" x="250" y="10" width="300" height="40"/><text class="label-bold" x="400" y="35">Breastfeeding Problem</text><line class="arrow" x1="320" y1="50" x2="150" y2="85"/><line class="arrow" x1="480" y1="50" x2="650" y2="85"/><rect class="box" x="30" y="85" width="240" height="45"/><text class="label-bold" x="150" y="105">Insufficient Milk</text><text class="label small" x="150" y="122">Stanya Kshaya</text><rect class="box-red" x="530" y="85" width="240" height="45"/><text class="label-bold" x="650" y="105">Breast Pain/Infection</text><text class="label small" x="650" y="122">Stana Roga / Mastitis</text><line class="arrow" x1="150" y1="130" x2="150" y2="170"/><line class="arrow" x1="650" y1="130" x2="650" y2="170"/><rect class="box-green" x="20" y="170" width="260" height="65"/><text class="label-bold" x="150" y="190">Stanyajanana Protocol</text><text class="label" x="150" y="207">Shatavari Kalpa, Vidarikanda</text><text class="label" x="150" y="222">Improve latch, frequent feeding</text><rect class="box-blue" x="520" y="170" width="260" height="65"/><text class="label-bold" x="650" y="190">Anti-inflammatory Protocol</text><text class="label" x="650" y="207">Ayurveda: Dashanga Lepa, cold compress</text><text class="label" x="650" y="222">Modern: antibiotics, I&D if abscess</text><rect class="box-green" x="150" y="300" width="500" height="50"/><text class="label-bold" x="400" y="323">Integrated: BFHI + Ayurvedic Stanya Paricharya</text><text class="label" x="400" y="340">WHO breastfeeding guidelines + Shatavari/Stanya Shodhana</text><line class="arrow" x1="150" y1="235" x2="300" y2="300"/><line class="arrow" x1="650" y1="235" x2="500" y2="300"/></svg>`,
      notes: `<p><strong>Key points:</strong></p><ul class="list-disc pl-5 mt-2 space-y-1"><li>Breastfeeding should be initiated within 1 hour of birth (WHO recommendation, aligns with Kashyapa's Jatakarma)</li><li>Exclusive breastfeeding for 6 months — complementary feeding only after 6 months</li><li>Shatavari is the most evidence-based Ayurvedic galactagogue</li><li>Mastitis: continue breastfeeding (emptying the breast helps). Antibiotics if fever >38°C for >24 hours</li><li>Stanya Shodhana: if breast milk is vitiated, purify mother with appropriate Dosha-specific treatment, not the milk itself</li></ul>`,
    },
    integration: `<h3 class="font-heading text-xl font-semibold text-saffron-800 mb-3">Stanya Vigyana — Ayurveda-Modern Integration</h3><div class="space-y-4"><p>Ayurveda's detailed Stanya Pareeksha (breast milk examination) and Stanya Dushti classification add a unique dimension to lactation assessment. Combined with modern understanding of hormonal regulation and BFHI protocols, an integrated approach provides superior breastfeeding support.</p><div class="bg-white/60 p-4 rounded-lg mt-4"><h4 class="font-semibold text-gray-800 mb-2">Clinical Protocol</h4><ol class="list-decimal pl-5 space-y-1 text-sm"><li>Assess Stanya with Ayurvedic Pareeksha + observe breastfeeding technique</li><li>If Stanya Kshaya: Shatavari Kalpa + correct latch + frequent feeding</li><li>If Stanya Dushti: identify Dosha type and treat mother accordingly</li><li>If mastitis: continue feeding + Dashanga Lepa + antibiotics if bacterial</li><li>Support: lactation counsellor + family education</li></ol></div></div>`,
    examBullets: [
      "Stanya is Upadhatu of Rasa Dhatu, flowing through Stanya Vaha Srotas (Charaka).",
      "Shuddha Stanya Lakshana: Avigandhi (no smell), Avivarna (no discoloration), Snigdha (unctuous), dissolves evenly in water.",
      "Stanya Pareeksha (water test): pure milk disperses evenly. Vataja floats/froths, Pittaja discolors, Kaphaja sinks.",
      "Stanyajanana drugs: Shatavari, Vidarikanda, Jivanti, Yashtimadhu (Charaka Sutra 25).",
      "Stanya Shodhana: purification of vitiated breast milk by treating the mother's Dosha, not the milk directly.",
      "Kashyapa says Stanya Dosha causes severe infant diseases — always examine milk before feeding.",
      "Modern lactation hormones: Prolactin (milk production, anterior pituitary), Oxytocin (let-down, posterior pituitary).",
      "Colostrum (Day 1-5): yellow, rich in IgA, lactoferrin, leukocytes. Called 'liquid gold' — Ayurveda calls it Ksheerapa.",
      "WHO/UNICEF BFHI: initiate within 1 hour, exclusive for 6 months, no prelacteals, demand feeding, room-in.",
      "Breast engorgement (Day 3-4): warm compress before feed, cold compress after. Continue feeding to resolve.",
      "Mastitis: Staphylococcal infection. Rx: continue breastfeeding + flucloxacillin. Abscess needs I&D.",
      "Galactocele: milk-filled cyst from blocked duct. Kaphaja Stanya Dushti correlate. Rx: aspiration.",
      "Cracked nipple: most common cause of breastfeeding failure. Rx: correct latch technique, lanolin cream.",
      "Contraindications to breastfeeding: HIV (in developed countries), active TB on treatment <2 weeks, certain drugs.",
      "Shatavari (Asparagus racemosus) mechanism: phytoestrogens increase prolactin and milk production.",
    ],
    mnemonics: [
      { title: "Stanyajanana Drugs", acronym: "SVJY", expansions: ["Shatavari (Asparagus racemosus)", "Vidarikanda (Pueraria tuberosa)", "Jivanti (Leptadenia reticulata)", "Yashtimadhu (Glycyrrhiza glabra)"] },
      { title: "Shuddha Stanya Lakshana", acronym: "AASW", expansions: ["Avigandhi — no abnormal smell", "Avivarna — no discoloration", "Snigdha — unctuous/smooth", "Water test — disperses evenly"] },
      { title: "BFHI Steps (Key)", acronym: "BIRD", expansions: ["Breastfeed within 1 hour", "Initiate demand feeding (no schedule)", "Room-in 24 hours", "Don't give prelacteals (no honey, water)"] },
    ],
  };
}
