import React from "react";
export function getM17Content() {
  return {
    references: ["Charaka Sharira Sthana Ch. 3", "Sushruta Sharira Sthana Ch. 2 & 3", "Ashtanga Hridaya Sharira Sthana Ch. 1", "Kashyapa Samhita — Revatikalpa Adhyaya", "DC Dutta Ch. 5", "Shaw's Textbook of Gynaecology Ch. 4"],
    units: [
      { title: "Artava Utpatti & Rituchakra", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Artava (menstrual blood) is the Upadhatu of Rasa Dhatu according to Sushruta and the Updhatu of Rakta Dhatu as per some Acharyas. This unit covers Artava Utpatti (menstrual physiology), Rituchakra (menstrual cycle), and the HPO axis correlation with Ayurvedic concepts."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Artava — Upadhatu formed from Rasa/Rakta Dhatu"), React.createElement("li", null, "• Artava Vaha Srotas — channels carrying menstrual fluid"), React.createElement("li", null, "• Rituchakra — Ritu Kala (menstrual phase), Ritu Vyatita Kala (proliferative), Ritumati Kala (ovulatory/secretory)"), React.createElement("li", null, "• HPO axis correlation: Vata (hypothalamus), Pitta (pituitary), Kapha (ovary)"))) },
      { title: "Artava Lakshana & Artava Dushti", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Shuddha Artava Lakshana (properties of normal menstrual blood) and Artava Dushti (vitiation of menstruation by Doshas). Classification of Artava Dushti into Vataja, Pittaja, Kaphaja, and Sannipataja types."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Shuddha Artava: resembles Gunja (Abrus) seed colour, Laksha Rasa (lac), or Indragopa (red insect)"), React.createElement("li", null, "• Duration: 5 days (Tridoshic range 3-7 days)"), React.createElement("li", null, "• Vataja: scanty, painful, dark, frothy menstruation"), React.createElement("li", null, "• Pittaja: excessive, hot, burning, yellowish-red flow"))) },
      { title: "Rajaswala Paricharya & Menstrual Disorders", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Rajaswala Paricharya (menstrual regimen) as described in classical texts. Modern classification of menstrual disorders and integrated management."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Rajaswala Paricharya: dietary and lifestyle regimen during menstruation"), React.createElement("li", null, "• Pathya: Yavaka (barley), Shali rice, Ghrita, light diet"), React.createElement("li", null, "• Apathya: Vyayama (exercise), Divaswapna (day sleep), Abhyanga (oil massage), Maithuna (coitus)"), React.createElement("li", null, "• Modern menstrual disorders: amenorrhoea, oligomenorrhoea, menorrhagia, dysmenorrhoea"))) },
      { title: "HPO Axis & Ovarian Cycle Integration", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Correlation of the Hypothalamic-Pituitary-Ovarian (HPO) axis with Ayurvedic Dosha physiology. Understanding GnRH, FSH, LH, estrogen, and progesterone in the context of Rituchakra."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• GnRH (Vata-driven pulsatility) → FSH/LH (Pitta — transformative hormones)"), React.createElement("li", null, "• Follicular phase (Kapha dominant — growth and nourishment)"), React.createElement("li", null, "• Ovulation (Pitta peak — LH surge, transformation)"), React.createElement("li", null, "• Luteal phase (Vata-Pitta — progesterone, secretory changes)"))) },
    ],
    orientation: { why: "Artava Vigyana bridges Ayurvedic menstrual physiology with modern reproductive endocrinology. Understanding Rituchakra alongside the HPO axis and menstrual cycle phases is fundamental to managing all gynaecological disorders in integrated practice.", examWeight: "Very high-yield. Long essays on Artava Utpatti, Shuddha Artava Lakshana, Rituchakra comparison, and Rajaswala Paricharya appear almost every year. Short notes on Artava Dushti types are equally common." },
    definition: {
      ayurveda: `<p><strong>Artava</strong> (menstrual blood/ovum) is the Upadhatu of Rasa Dhatu (Sushruta) or Rakta Dhatu (some Acharyas). It is produced monthly under the influence of Agni and Vayu, flows through Artava Vaha Srotas, and is expelled cyclically as Rajah (menstruation).</p><p class="mt-2">Sushruta describes the Rituchakra (menstrual cycle) in three phases: <strong>Rajah Kala</strong> (menstrual phase), <strong>Ritu Vyatita Kala</strong> (proliferative phase), and <strong>Ritumati Kala</strong> (fertile/ovulatory period).</p>`,
      modern: `<p><strong>Menstruation</strong> is the cyclical shedding of the endometrial lining occurring every 21-35 days (average 28 days). The menstrual cycle is regulated by the <strong>HPO axis</strong>:<br/><strong>Menstrual phase:</strong> Days 1-5 (endometrial shedding)<br/><strong>Proliferative phase:</strong> Days 6-14 (estrogen-driven endometrial growth)<br/><strong>Secretory phase:</strong> Days 15-28 (progesterone-dominant, glandular secretion)</p><p class="mt-2">Ovulation occurs around Day 14, triggered by the LH surge. The corpus luteum produces progesterone to maintain the secretory endometrium.</p>`,
    },
    shlokas: [
      { source: "Sushruta Sharira Sthana 2/18", devanagari: "आर्तवं शोणितं यत्तु रजोभूतं प्रवर्तते |\nद्वादशात् वर्षात् यावत् पञ्चाशतं वर्षं भवेत् ||", transliteration: "ārtavaṃ śoṇitaṃ yattu rajobhūtaṃ pravartate |\ndvādaśāt varṣāt yāvat pañcāśataṃ varṣaṃ bhavet ||", meaning: "Artava (menstrual blood), which is a form of Rakta (blood), begins to flow from the age of 12 years and continues up to the age of 50 years.", clinicalNote: "This precisely defines menarche (12 years) and menopause (50 years) — remarkably aligned with modern understanding of the reproductive lifespan." },
      { source: "Sushruta Sharira Sthana 2/19", devanagari: "यत्तद् गुञ्जाफलाभासं लाक्षारसनिभं च यत् |\nइन्द्रगोपसवर्णं च तदृतौ शुद्धमार्तवम् ||", transliteration: "yattad guñjāphalābhāsaṃ lākṣārasanibhaṃ ca yat |\nindragopasavarṇaṃ ca tadṛtau śuddhamārtavam ||", meaning: "Shuddha Artava (pure menstrual blood) resembles the colour of Gunja fruit (Abrus precatorius), Laksha Rasa (lac juice), or Indragopa (red insect/cochineal). Such Artava is considered pure during the menstrual period.", clinicalNote: "The Shuddha Artava Lakshana describes bright red colour without abnormal clots — corresponding to normal menstrual blood of moderate flow." },
      { source: "Charaka Chikitsa Sthana 30/225-226", devanagari: "ऋतुकाले प्रकुपितैर्दोषैरार्तवमाश्रितम् |\nदुष्यत्यनेकैराकारैर्यथास्वं दोषलक्षणैः ||", transliteration: "ṛtukāle prakupitairdoṣairārtavamāśritam |\nduṣyatyanekairākārairyathāsvaṃ doṣalakṣaṇaiḥ ||", meaning: "During the menstrual period, when the Doshas are aggravated, Artava becomes vitiated and manifests various abnormalities according to the respective Dosha characteristics.", clinicalNote: "This is the foundational shloka for Artava Dushti classification — Vataja (scanty, painful), Pittaja (excessive, hot), Kaphaja (mucoid, heavy), and Sannipataja (mixed features)." },
      { source: "Ashtanga Sangraha Sharira Sthana 1/24", devanagari: "रजस्वलां त्र्यहं ब्रह्मचारिणीमशनां शयानां दर्भसंस्तरे |\nहविष्याशिनीं पात्रे करतलेन अन्नं भुञ्जानाम् ||", transliteration: "rajasvalāṃ tryahaṃ brahmacāriṇīmaśanāṃ śayānāṃ darbhasaṃstare |\nhaviṣyāśinīṃ pātre karatalena annaṃ bhuñjānām ||", meaning: "The menstruating woman (Rajaswala) should observe celibacy for three days, sleep on a mat of Darbha grass, eat Havishy anna (sacrificial food — simple, light), and take food from the palm of her hand.", clinicalNote: "Rajaswala Paricharya emphasizes rest, light diet, and reduced physical activity — aligning with modern recommendations to avoid strenuous exercise during heavy menstrual flow and to maintain nutritional support." },
    ],
    dualCols: [
      { title: "Menstrual Cycle Phases", ayurvedaTitle: "Rituchakra", modernTitle: "Modern Menstrual Cycle", ayurvedaContent: `<p><strong>Rituchakra Phases:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Rajah Kala (Days 1-3/5):</strong> Vata dominant — expulsion of menstrual blood (Apana Vayu)</li><li><strong>Ritu Vyatita Kala (Days 4-12):</strong> Kapha dominant — regeneration, nourishment of Rasa-Rakta Dhatu</li><li><strong>Ritumati Kala (Days 12-16):</strong> Pitta dominant — peak fertility, Artava ready for conception</li></ul><p class="mt-2"><strong>Dosha-cycle correlation:</strong></p><ul class="list-disc pl-4 space-y-1"><li>Vata: menstrual phase (movement, downward flow)</li><li>Kapha: follicular phase (growth, nourishment)</li><li>Pitta: ovulatory/luteal (transformation, heat)</li></ul>`, modernContent: `<p><strong>Menstrual cycle phases (28-day model):</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Menstrual phase (Days 1-5):</strong> Endometrial shedding due to progesterone withdrawal</li><li><strong>Proliferative phase (Days 6-14):</strong> Estrogen from growing follicles → endometrial growth</li><li><strong>Ovulation (Day 14):</strong> LH surge → follicle rupture → oocyte release</li><li><strong>Secretory phase (Days 15-28):</strong> Corpus luteum → progesterone → glandular secretion</li></ul><p class="mt-2"><strong>HPO axis:</strong> GnRH (hypothalamus) → FSH + LH (pituitary) → Estrogen + Progesterone (ovary) → Endometrial changes</p>` },
    ],
    clinicalFeatures: [{ title: "Artava Dushti — Dosha-wise Classification", headers: ["Type", "Menstrual Features", "Associated Symptoms", "Modern Correlation"], rows: [["<strong>Vataja</strong>", "Scanty (Alpa), dark/blackish, frothy (Phenila), delayed", "Severe pain (Vedana), stiffness, flatulence", "Oligomenorrhoea, dysmenorrhoea, scanty flow"], ["<strong>Pittaja</strong>", "Excessive (Bahu), hot, yellowish-red, frequent", "Burning (Daha), fever, foul smell", "Menorrhagia, polymenorrhoea, infections"], ["<strong>Kaphaja</strong>", "Mucoid (Picchila), pale, heavy, prolonged", "Heaviness, nausea, cold, oedema", "Mucoid discharge, DUB with anovulation"], ["<strong>Sannipataja</strong>", "Mixed features of all three Doshas", "Variable symptoms, poor prognosis", "Complex AUB, hormonal imbalance"]] }],
    investigations: [{ title: "Menstrual Disorder Investigations", headers: ["Investigation", "Purpose", "Indication"], rows: [["<strong>Artava Pareeksha</strong>", "Assess colour, consistency, odour of menstrual blood", "Routine Ayurvedic gynaecological assessment"], ["<strong>Pelvic USG</strong>", "Evaluate uterus, ovaries, endometrial thickness", "AUB, suspected PCOS, fibroids"], ["<strong>Hormonal panel (FSH, LH, E2, Progesterone)</strong>", "Assess HPO axis function", "Amenorrhoea, oligomenorrhoea, infertility"], ["<strong>Thyroid profile (TSH, T3, T4)</strong>", "Rule out thyroid dysfunction", "Menstrual irregularities, unexplained AUB"], ["<strong>Endometrial biopsy</strong>", "Histopathological assessment of endometrium", "AUB >40 years, suspected hyperplasia/malignancy"]] }],
    management: {
      diagramTitle: "Menstrual Disorder — Integrated Management Algorithm",
      diagramSvg: `<svg viewBox="0 0 800 440" xmlns="http://www.w3.org/2000/svg" class="w-full max-w-3xl"><style>.box{fill:#FFF8E1;stroke:#C8712A;stroke-width:2;rx:10}.box-blue{fill:#E3F2FD;stroke:#42A5F5;stroke-width:2;rx:10}.box-green{fill:#E8F5E9;stroke:#66BB6A;stroke-width:2;rx:10}.box-red{fill:#FFEBEE;stroke:#EF5350;stroke-width:2;rx:10}.label{font-family:'DM Sans',sans-serif;font-size:12px;fill:#333;text-anchor:middle}.label-bold{font-family:'DM Sans',sans-serif;font-size:13px;fill:#333;font-weight:bold;text-anchor:middle}.arrow{stroke:#C8712A;stroke-width:2;fill:none;marker-end:url(#ah17)}.small{font-size:11px}</style><defs><marker id="ah17" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto"><polygon points="0 0,10 3.5,0 7" fill="#C8712A"/></marker></defs><rect class="box" x="250" y="10" width="300" height="40"/><text class="label-bold" x="400" y="35">Artava Dushti / Menstrual Disorder</text><line class="arrow" x1="320" y1="50" x2="150" y2="85"/><line class="arrow" x1="480" y1="50" x2="650" y2="85"/><rect class="box" x="30" y="85" width="240" height="45"/><text class="label-bold" x="150" y="105">Vataja (Scanty/Painful)</text><text class="label small" x="150" y="122">Oligomenorrhoea / Dysmenorrhoea</text><rect class="box-red" x="530" y="85" width="240" height="45"/><text class="label-bold" x="650" y="105">Pittaja (Excessive/Hot)</text><text class="label small" x="650" y="122">Menorrhagia / Polymenorrhoea</text><line class="arrow" x1="150" y1="130" x2="150" y2="170"/><line class="arrow" x1="650" y1="130" x2="650" y2="170"/><rect class="box-green" x="20" y="170" width="260" height="75"/><text class="label-bold" x="150" y="190">Vata Shamana Protocol</text><text class="label" x="150" y="207">Dashamoola Kwatha, Shatavari</text><text class="label" x="150" y="222">Basti Chikitsa (Anuvasana)</text><text class="label" x="150" y="237">Modern: NSAIDs, OCP, hormones</text><rect class="box-blue" x="520" y="170" width="260" height="75"/><text class="label-bold" x="650" y="190">Pitta Shamana Protocol</text><text class="label" x="650" y="207">Ashoka, Lodhra, Nagakeshara</text><text class="label" x="650" y="222">Ushirasava, Chandanasava</text><text class="label" x="650" y="237">Modern: Tranexamic acid, OCPs</text><rect class="box" x="250" y="290" width="300" height="45"/><text class="label-bold" x="400" y="310">Kaphaja (Mucoid/Heavy)</text><text class="label small" x="400" y="327">Anovulatory bleeding, mucoid discharge</text><line class="arrow" x1="400" y1="335" x2="400" y2="370"/><rect class="box-green" x="200" y="370" width="400" height="55"/><text class="label-bold" x="400" y="390">Kapha Shamana + Integrated Care</text><text class="label" x="400" y="407">Triphala, Kanchanara, Trikatu + Rajaswala Paricharya</text><text class="label" x="400" y="420">Modern: Progesterone, Clomiphene for anovulation</text></svg>`,
      notes: `<p><strong>Key points:</strong></p><ul class="list-disc pl-5 mt-2 space-y-1"><li>Artava Dushti management is always Dosha-specific — identify the predominant Dosha first</li><li>Vataja: Snehana, Swedana, Basti (Dashamoola Kwatha), Shatavari — modern: mefenamic acid, OCPs</li><li>Pittaja: Sheeta Virya drugs (Ashoka, Lodhra, Chandana) — modern: tranexamic acid, progesterone</li><li>Kaphaja: Lekhana, Shodhana (Vamana if needed) — modern: progesterone for anovulatory cycles</li><li>Rajaswala Paricharya should be advised to all patients as a preventive and supportive measure</li></ul>`,
    },
    integration: `<h3 class="font-heading text-xl font-semibold text-saffron-800 mb-3">Artava Vigyana — Ayurveda-Modern Integration</h3><div class="space-y-4"><p>The Ayurvedic Rituchakra provides a Dosha-based framework for understanding the menstrual cycle that remarkably parallels modern endocrinology. Vata governs the menstrual phase (downward movement), Kapha governs the proliferative phase (growth), and Pitta governs ovulation and the secretory phase (transformation). Integrating Artava Pareeksha with hormonal investigations enables precise, personalised menstrual disorder management.</p><div class="bg-white/60 p-4 rounded-lg mt-4"><h4 class="font-semibold text-gray-800 mb-2">Clinical Protocol</h4><ol class="list-decimal pl-5 space-y-1 text-sm"><li>Assess Artava Lakshana (colour, quantity, duration, pain) + hormonal panel</li><li>Classify Artava Dushti by Dosha type and correlate with modern diagnosis</li><li>Vataja: Dashamoola Kwatha Basti + NSAIDs for dysmenorrhoea</li><li>Pittaja: Ashokarishta/Lodhra + tranexamic acid for menorrhagia</li><li>Advise Rajaswala Paricharya as lifestyle modification for all patients</li></ol></div></div>`,
    examBullets: [
      "Artava is Upadhatu of Rasa Dhatu (Sushruta) — some Acharyas consider it Upadhatu of Rakta Dhatu.",
      "Artava Vaha Srotas: Moola — Garbhashaya (uterus) and Artava Vahi Dhamanis (ovarian/uterine arteries).",
      "Shuddha Artava Lakshana: colour of Gunja, Laksha Rasa, or Indragopa; not excessive; washes out of cloth (Sushruta).",
      "Artava Kala: begins at age 12 (menarche), ceases at age 50 (menopause) — Sushruta Sharira 2/18.",
      "Rituchakra: Rajah Kala (Days 1-5, Vata), Ritu Vyatita Kala (Days 6-12, Kapha), Ritumati Kala (Days 12-16, Pitta).",
      "HPO axis Dosha correlation: Vata (hypothalamic GnRH pulsatility), Pitta (pituitary FSH/LH), Kapha (ovarian folliculogenesis).",
      "Vataja Artava Dushti: Alpa (scanty), Krishna (dark), Phenila (frothy), Vedana (painful) — correlates with dysmenorrhoea.",
      "Pittaja Artava Dushti: Bahu (excess), Ushna (hot), Peeta/Neela (yellowish/bluish) — correlates with menorrhagia.",
      "Kaphaja Artava Dushti: Picchila (mucoid), Pandu (pale), Guru (heavy) — correlates with anovulatory DUB.",
      "Rajaswala Paricharya: rest on Darbha, Havishy anna, celibacy, no oil bath, no day sleep for 3 days.",
      "Modern menstrual phase: progesterone withdrawal → spiral artery spasm → endometrial ischaemia → shedding.",
      "LH surge triggers ovulation on Day 14. Corpus luteum forms and secretes progesterone for 14 days.",
      "Ashoka (Saraca asoca) is the premier Ayurvedic drug for menstrual disorders — has uterine tonic and hemostatic properties.",
      "Rajapravartini Vati is the classical Ayurvedic formulation for Artava Kshaya (scanty/absent menses).",
      "Normal menstrual blood loss: 30-80 mL. >80 mL = menorrhagia. MBL assessed by PBAC score (pictorial blood assessment chart).",
    ],
    mnemonics: [
      { title: "Shuddha Artava Lakshana", acronym: "GLIB", expansions: ["Gunja-coloured (bright red)", "Laksha Rasa-like (lac juice)", "Indragopa-resembling (red insect colour)", "Bhasmani na lepayati — does not stain cloth permanently"] },
      { title: "Rituchakra Phases", acronym: "RRR", expansions: ["Rajah Kala — menstrual phase (Vata, Days 1-5)", "Ritu Vyatita Kala — proliferative (Kapha, Days 6-12)", "Ritumati Kala — fertile/ovulatory (Pitta, Days 12-16)"] },
      { title: "Artava Dushti Features", acronym: "SHEM", expansions: ["Scanty-dark-painful = Vataja", "Hot-excessive-burning = Pittaja", "Eavy(Heavy)-mucoid-pale = Kaphaja", "Mixed features = Sannipataja"] },
      { title: "Rajaswala Paricharya Don'ts", acronym: "DOME", expansions: ["Divaswapna (no day sleep)", "Oil massage (no Abhyanga)", "Maithuna (no coitus)", "Exercise (no Vyayama)"] },
    ],
  };
}
