import React from "react";
export function getM29Content() {
  return {
    references: ["Charaka Sharira Sthana Ch. 4", "Sushruta Sharira Sthana Ch. 3", "Ashtanga Hridaya Sharira Sthana Ch. 1", "Kashyapa Samhita — Sharira Sthana", "Guyton & Hall — Reproductive Physiology Ch. 82", "DC Dutta Ch. 4"],
    units: [
      { title: "Artava Utpatti & Rituchakra", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Artava (menstrual blood/ovum) is the Upadhatu of Rasa Dhatu. Rituchakra (menstrual cycle) is described in Ayurvedic texts with specific phases. This unit covers Artava Utpatti (formation), Artava Srava Kala (menstrual period), and the concept of Ritukala (fertile period)."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Artava as Upadhatu of Rasa Dhatu — Charaka & Sushruta views"), React.createElement("li", null, "• Rituchakra — Rajahsrava Kala (menstrual phase), Ritukala (proliferative/fertile), Rituvyatita Kala (secretory)"), React.createElement("li", null, "• Artava Lakshana — properties of Shuddha Artava"), React.createElement("li", null, "• Modern correlation: ovarian cycle (follicular, ovulation, luteal) and endometrial cycle"))) },
      { title: "HPO Axis & Hormonal Regulation", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "The Hypothalamic-Pituitary-Ovarian (HPO) axis controls the menstrual cycle through feedback mechanisms. Ayurveda explains this through Vata-Pitta-Kapha regulation and Dhatu Parinamana."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• GnRH from hypothalamus → FSH & LH from anterior pituitary → ovarian response"), React.createElement("li", null, "• Estrogen (Pitta correlation) — endometrial proliferation, follicle maturation"), React.createElement("li", null, "• Progesterone (Kapha correlation) — secretory changes, pregnancy maintenance"), React.createElement("li", null, "• LH surge → ovulation; negative & positive feedback mechanisms"))) },
      { title: "Rajodharshana (Menarche) & Rajonivrutti (Menopause)", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Rajodharshana (menarche) marks the onset of menstrual function, while Rajonivrutti (menopause) marks its cessation. Ayurvedic texts describe age-specific milestones and Dosha predominance at different life stages."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Rajodharshana at age 12 (Sushruta) — onset of Pitta Kala"), React.createElement("li", null, "• Rajonivrutti at age 50 (Sushruta Sharira 3) — onset of Vata Kala"), React.createElement("li", null, "• Modern: menarche 10-16 years, menopause 45-55 years"), React.createElement("li", null, "• Thelarche, pubarche, growth spurt — Tanner staging correlation"))) },
    ],
    orientation: { why: "Understanding Stree Kriya Sharira (female reproductive physiology) is fundamental to all of OBGYN practice. The Ayurvedic concepts of Artava, Rituchakra, and Rajodharshana/Rajonivrutti provide a unique Doshic framework that integrates beautifully with modern HPO axis physiology.", examWeight: "Very high-yield. Long answers on Artava Utpatti, Rituchakra with modern correlation, HPO axis, and ovarian/endometrial cycle are frequent. Short notes on Rajodharshana, Shuddha Artava Lakshana, and hormones appear almost every session." },
    definition: {
      ayurveda: `<p><strong>Stree Kriya Sharira</strong> encompasses the physiological functions unique to the female body — primarily Artava (menstrual blood/ovum), Rituchakra (menstrual cycle), Rajodharshana (menarche), and Rajonivrutti (menopause). Artava is an Upadhatu of Rasa Dhatu, governed by Apana Vayu, Pitta (Ranjaka & Pachaka), and Kapha.</p><p class="mt-2">Sushruta describes the Rituchakra in three phases: Rajahsrava Kala (3 days), Ritukala (12 days — fertile period), and Rituvyatita Kala (remaining days). The entire cycle spans one lunar month.</p>`,
      modern: `<p><strong>Female Reproductive Physiology</strong> is governed by the HPO axis. The menstrual cycle (average 28 days) consists of:<br/><strong>Ovarian cycle:</strong> Follicular phase → Ovulation → Luteal phase<br/><strong>Endometrial cycle:</strong> Menstrual → Proliferative → Secretory phase</p><p class="mt-2">Key hormones: GnRH (hypothalamus), FSH & LH (anterior pituitary), Estrogen & Progesterone (ovary). The LH surge triggers ovulation on Day 14. Puberty begins with pulsatile GnRH secretion; menopause occurs when follicular reserve is depleted.</p>`,
    },
    shlokas: [
      { source: "Sushruta Sharira Sthana 3/11", devanagari: "रसात् स्तन्यं ततो रक्तं रक्तात् मांसं ततो मेदः |\nआर्तवं रसजं प्रोक्तं उपधातु विशेषतः ||", transliteration: "rasāt stanyaṃ tato raktaṃ raktāt māṃsaṃ tato medaḥ |\nārtavaṃ rasajaṃ proktaṃ upadhātu viśeṣataḥ ||", meaning: "From Rasa Dhatu, Stanya (breast milk) and Artava (menstrual blood) are formed as Upadhatus. Artava is specifically declared as the Upadhatu of Rasa Dhatu.", clinicalNote: "This shloka establishes the fundamental origin of Artava. Since Artava depends on Rasa Dhatu quality, nutritional status (Ahara-Rasa) directly affects menstrual health — a concept validated by modern understanding of hypothalamic amenorrhea in malnutrition." },
      { source: "Sushruta Sharira Sthana 3/6", devanagari: "द्वादशे वर्षे राजः प्रवर्तते स्त्रीणां |\nपञ्चाशत्तमे वर्षे राजो निवर्तते ||", transliteration: "dvādaśe varṣe rājaḥ pravartate strīṇāṃ |\npañcāśattame varṣe rājo nivartate ||", meaning: "Menstruation commences in women at the age of 12 years (Rajodharshana/menarche) and ceases at the age of 50 years (Rajonivrutti/menopause).", clinicalNote: "Sushruta's menarche age of 12 closely matches the modern average of 12.5 years. The menopause age of 50 is remarkably accurate compared to the current average of 51 years. This demonstrates the precision of ancient clinical observations." },
      { source: "Sushruta Sharira Sthana 2/18", devanagari: "शुद्धं शोणितमिच्छन्ति यत् शशासनसन्निभम् |\nयत् पद्मरसवर्णं वा यत् लाक्षारससन्निभम् ||", transliteration: "śuddhaṃ śoṇitamicchanti yat śaśāsanasannibham |\nyat padmarasavarṇaṃ vā yat lākṣārasasannibham ||", meaning: "Pure Artava (menstrual blood) resembles the colour of Shashasana (red lotus/lac dye), Padmarasa (lotus juice), or Laksha Rasa (lac dye) — bright red, not too dark nor pale.", clinicalNote: "Shuddha Artava Lakshana is a classic exam topic. Normal menstrual blood should be bright red, non-foul smelling, neither excessive nor scanty, and should not stain cloth permanently (washes out). These criteria help clinically assess menstrual health." },
      { source: "Ashtanga Sangraha Sharira 1/19", devanagari: "ऋतुकालस्तु द्वादशरात्रः स्त्रीणाम् |\nतत्र प्रथमत्रिरात्रं तु अनुपयोग्यम् ||", transliteration: "ṛtukālastu dvādaśarātraḥ strīṇām |\ntatra prathamatrirātraṃ tu anupayogyam ||", meaning: "The Ritukala (fertile period) of women is twelve nights. The first three nights (Rajahsrava Kala/menstruation) are not suitable for conception.", clinicalNote: "Ayurveda divides the cycle into Rajahsrava Kala (Day 1-3, menstruation), Ritukala (Day 4-16, fertile window), and Rituvyatita Kala (remaining days). The concept of a mid-cycle fertile window remarkably parallels modern understanding of the ovulatory period." },
    ],
    dualCols: [
      { title: "Menstrual Cycle Physiology", ayurvedaTitle: "Rituchakra (Ayurveda)", modernTitle: "Menstrual Cycle (Modern)", ayurvedaContent: `<p><strong>Rituchakra Phases:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Rajahsrava Kala (Day 1-3):</strong> Menstrual bleeding; Vata (Apana Vayu) dominant; abstinence prescribed</li><li><strong>Ritukala (Day 4-16):</strong> Fertile period; Pitta-Kapha phase; Rasa-Rakta nourishment; best for conception</li><li><strong>Rituvyatita Kala (Day 17-30):</strong> Infertile phase; Vata dominant again; Artava diminishes</li></ul><p class="mt-2"><strong>Artava regulation:</strong> Apana Vayu → Artava Sravana; Ranjaka Pitta → Artava colour; Kapha → Artava nourishment</p>`, modernContent: `<p><strong>Ovarian Cycle:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Follicular phase (Day 1-14):</strong> FSH → follicle growth → Graafian follicle; rising estrogen</li><li><strong>Ovulation (Day 14):</strong> LH surge → ovum release from dominant follicle</li><li><strong>Luteal phase (Day 15-28):</strong> Corpus luteum → progesterone; endometrial secretory changes</li></ul><p class="mt-2"><strong>Endometrial Cycle:</strong> Menstrual (Day 1-5) → Proliferative (Day 6-14, estrogen-driven) → Secretory (Day 15-28, progesterone-driven)</p>` },
    ],
    clinicalFeatures: [{ title: "Shuddha vs Dushta Artava — Comparative Features", headers: ["Parameter", "Shuddha Artava", "Dushta Artava", "Modern Correlation"], rows: [["<strong>Colour</strong>", "Shashasana/Padmarasa (bright red)", "Pale, dark brown, or blackish", "Normal vs abnormal menstrual colour"], ["<strong>Odour</strong>", "No foul smell (Avigandhi)", "Foul-smelling (Durgandhi)", "Infection/endometritis"], ["<strong>Quantity</strong>", "Moderate (5 Anjali)", "Excessive or scanty", "Menorrhagia/hypomenorrhea"], ["<strong>Duration</strong>", "5 days (Sushruta)", "Prolonged or too short", "Normal 3-7 days"], ["<strong>Stain test</strong>", "Washes out of cloth", "Permanently stains", "Normal blood vs pathological discharge"]] }],
    investigations: [{ title: "Female Reproductive Physiology — Investigations", headers: ["Investigation", "Purpose", "Normal Value/Finding"], rows: [["<strong>Serum FSH</strong>", "Assess ovarian reserve, menopausal status", "Follicular: 3-10 IU/L; Menopause: >40 IU/L"], ["<strong>Serum LH</strong>", "Confirm ovulation, PCOS diagnosis", "Mid-cycle surge: 20-100 IU/L"], ["<strong>Serum Estradiol (E2)</strong>", "Follicle maturation, endometrial status", "Follicular: 30-100 pg/mL; Preovulatory: 100-400 pg/mL"], ["<strong>Serum Progesterone (Day 21)</strong>", "Confirm ovulation", ">3 ng/mL confirms ovulation; >10 ng/mL adequate luteal function"], ["<strong>Pelvic USG</strong>", "Follicular monitoring, endometrial thickness", "Dominant follicle: 18-25mm; Endometrium: 8-14mm mid-cycle"]] }],
    management: {
      diagramTitle: "HPO Axis & Rituchakra — Integrated Diagram",
      diagramSvg: `<svg viewBox="0 0 800 450" xmlns="http://www.w3.org/2000/svg" class="w-full max-w-3xl"><style>.box{fill:#FFF8E1;stroke:#C8712A;stroke-width:2;rx:10}.box-blue{fill:#E3F2FD;stroke:#42A5F5;stroke-width:2;rx:10}.box-green{fill:#E8F5E9;stroke:#66BB6A;stroke-width:2;rx:10}.box-pink{fill:#FCE4EC;stroke:#EC407A;stroke-width:2;rx:10}.label{font-family:'DM Sans',sans-serif;font-size:12px;fill:#333;text-anchor:middle}.label-bold{font-family:'DM Sans',sans-serif;font-size:13px;fill:#333;font-weight:bold;text-anchor:middle}.arrow{stroke:#C8712A;stroke-width:2;fill:none;marker-end:url(#ah29)}.small{font-size:11px}</style><defs><marker id="ah29" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto"><polygon points="0 0,10 3.5,0 7" fill="#C8712A"/></marker></defs><rect class="box" x="280" y="10" width="240" height="40"/><text class="label-bold" x="400" y="35">Hypothalamus (GnRH)</text><line class="arrow" x1="400" y1="50" x2="400" y2="80"/><rect class="box-blue" x="280" y="80" width="240" height="40"/><text class="label-bold" x="400" y="105">Anterior Pituitary (FSH/LH)</text><line class="arrow" x1="320" y1="120" x2="180" y2="165"/><line class="arrow" x1="480" y1="120" x2="620" y2="165"/><rect class="box-pink" x="80" y="165" width="200" height="50"/><text class="label-bold" x="180" y="185">Ovarian Cycle</text><text class="label small" x="180" y="202">Follicular → Ovulation → Luteal</text><rect class="box-green" x="520" y="165" width="200" height="50"/><text class="label-bold" x="620" y="185">Endometrial Cycle</text><text class="label small" x="620" y="202">Menstrual → Prolif. → Secretory</text><line class="arrow" x1="180" y1="215" x2="180" y2="260"/><line class="arrow" x1="620" y1="215" x2="620" y2="260"/><rect class="box" x="60" y="260" width="240" height="55"/><text class="label-bold" x="180" y="280">Estrogen & Progesterone</text><text class="label small" x="180" y="297">Pitta (Estrogen) | Kapha (Progesterone)</text><rect class="box" x="500" y="260" width="240" height="55"/><text class="label-bold" x="620" y="280">Ayurvedic Correlation</text><text class="label small" x="620" y="297">Rajahsrava → Ritukala → Rituvyatita</text><rect class="box-pink" x="200" y="370" width="400" height="55"/><text class="label-bold" x="400" y="392">Integrated: Rituchakra = Ovarian + Endometrial Cycle</text><text class="label" x="400" y="410">Vata (menstrual) → Pitta-Kapha (proliferative) → Vata (secretory)</text><line class="arrow" x1="180" y1="315" x2="320" y2="370"/><line class="arrow" x1="620" y1="315" x2="480" y2="370"/></svg>`,
      notes: `<p><strong>Key points:</strong></p><ul class="list-disc pl-5 mt-2 space-y-1"><li>Artava is Upadhatu of Rasa Dhatu — hence nutrition directly affects menstrual health</li><li>Rituchakra has 3 Kala: Rajahsrava (menstrual), Ritukala (fertile), Rituvyatita (post-ovulatory)</li><li>HPO axis feedback: low estrogen → increased FSH; high estrogen → LH surge → ovulation</li><li>Rajodharshana at 12 years (Sushruta) matches modern menarche average of 12.5 years</li><li>Shuddha Artava: bright red, odourless, moderate quantity, washes out of cloth — 5 criteria</li></ul>`,
    },
    integration: `<h3 class="font-heading text-xl font-semibold text-saffron-800 mb-3">Stree Kriya Sharira — Ayurveda-Modern Integration</h3><div class="space-y-4"><p>The Ayurvedic Rituchakra framework provides a Doshic lens to understand the menstrual cycle. The Rajahsrava-Ritukala-Rituvyatita classification maps elegantly onto the modern menstrual-proliferative-secretory phases. Integrating HPO axis physiology with Dosha dynamics enables a holistic understanding of female reproductive health.</p><div class="bg-white/60 p-4 rounded-lg mt-4"><h4 class="font-semibold text-gray-800 mb-2">Clinical Protocol</h4><ol class="list-decimal pl-5 space-y-1 text-sm"><li>Assess Artava with Shuddha Artava Lakshana criteria + menstrual history</li><li>Correlate Dosha phase with cycle day (Vata = menstrual, Pitta-Kapha = proliferative/fertile)</li><li>Hormonal investigations (FSH, LH, E2, Progesterone) for ovulatory assessment</li><li>Pelvic USG for follicular monitoring and endometrial thickness</li><li>Treat cycle disorders by addressing Dosha imbalance + hormonal correction as needed</li></ol></div></div>`,
    examBullets: [
      "Artava is Upadhatu of Rasa Dhatu, regulated by Apana Vayu (Charaka, Sushruta).",
      "Shuddha Artava Lakshana: Shashasana-varna (bright red), Avigandhi, moderate (5 Anjali), 5-day duration, washes out of cloth.",
      "Rituchakra has 3 phases: Rajahsrava Kala (Day 1-3), Ritukala (Day 4-16, fertile), Rituvyatita Kala (Day 17-30).",
      "Rajodharshana (menarche) at 12 years and Rajonivrutti (menopause) at 50 years — Sushruta Sharira 3.",
      "HPO axis: Hypothalamus (GnRH) → Anterior Pituitary (FSH/LH) → Ovary (Estrogen/Progesterone).",
      "Ovarian cycle: Follicular phase (FSH, Day 1-14) → Ovulation (LH surge, Day 14) → Luteal phase (progesterone, Day 15-28).",
      "Endometrial cycle: Menstrual → Proliferative (estrogen) → Secretory (progesterone) phases.",
      "Estrogen functions: endometrial proliferation, cervical mucus (Spinnbarkeit), secondary sexual characters.",
      "Progesterone functions: secretory endometrium, raised BBT, decidualization, pregnancy maintenance.",
      "LH surge triggers ovulation — positive feedback of high estrogen on anterior pituitary.",
      "FSH stimulates follicular growth; inhibin B from granulosa cells provides negative feedback on FSH.",
      "Apana Vayu governs Artava Sravana (menstrual flow), Garbha Dharana (conception), and Prasava (delivery).",
      "Tanner staging: Thelarche (breast bud, Stage 2) is first sign of puberty; menarche occurs at Stage 3-4.",
      "Day 21 serum progesterone >3 ng/mL confirms ovulation; >10 ng/mL indicates adequate luteal support.",
      "Rajonivrutti (menopause): FSH >40 IU/L, low estradiol, cessation of menses for 12 months.",
    ],
    mnemonics: [
      { title: "HPO Axis Hormones", acronym: "GFL-EP", expansions: ["GnRH (hypothalamus)", "FSH (anterior pituitary)", "LH (anterior pituitary)", "Estrogen (ovary — follicle/theca cells)", "Progesterone (ovary — corpus luteum)"] },
      { title: "Shuddha Artava Lakshana", acronym: "CROWD", expansions: ["Colour — Shashasana/bright red", "Regular flow — 5 days", "Odourless (Avigandhi)", "Washes out of cloth (no permanent stain)", "Dosage moderate — 5 Anjali quantity"] },
      { title: "Rituchakra Phases", acronym: "RRR", expansions: ["Rajahsrava Kala (Day 1-3, menstrual, Vata)", "Ritukala (Day 4-16, fertile, Pitta-Kapha)", "Rituvyatita Kala (Day 17-30, infertile, Vata)"] },
      { title: "Estrogen Actions (Key)", acronym: "SPEC", expansions: ["Secondary sexual characters", "Proliferative endometrium", "Elasticity of cervical mucus (Spinnbarkeit)", "Calcium retention in bones"] },
    ],
  };
}
