import React from "react";
export function getM30Content() {
  return {
    references: ["Charaka Siddhi Sthana Ch. 9 & 12", "Sushruta Chikitsa Sthana Ch. 37", "Ashtanga Hridaya Uttara Tantra Ch. 34", "Kashyapa Samhita — Revati Kalpa", "Yogaratnakara — Yonivyapad Chikitsa", "DC Dutta Ch. 34"],
    units: [
      { title: "Uttara Basti in Stree Roga", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Uttara Basti is the most important Panchakarma procedure in gynaecology. It involves administration of medicated oil/decoction through the intrauterine route. Charaka Siddhi Sthana 12 describes it in detail for Yonivyapad and Vandhyatva."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Uttara Basti Vidhi — procedure, Yantra (instruments), Kala (timing — Ritukala)"), React.createElement("li", null, "• Sneha Uttara Basti — medicated oils (Phala Ghrita, Shatapushpa Taila)"), React.createElement("li", null, "• Kashaya Uttara Basti — decoctions (Dashamoola Kwatha)"), React.createElement("li", null, "• Indications: Vandhyatva, Artava Vyapada, Yonivyapad, tubal blockage"))) },
      { title: "Yoni Prakshalana, Pichu, Varti & Dhupana", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Sthanika Chikitsa (local therapies) form the backbone of Ayurvedic gynaecological treatment. These include vaginal douche (Prakshalana), tampons (Pichu), suppositories (Varti), and fumigation (Dhupana)."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Yoni Prakshalana — vaginal douche with Panchavalkala/Triphala Kashaya"), React.createElement("li", null, "• Yoni Pichu — oil-soaked tampon (Jatyadi Taila, Phala Ghrita)"), React.createElement("li", null, "• Yoni Varti — vaginal suppositories (medicated wicks)"), React.createElement("li", null, "• Yoni Dhupana — fumigation with Guggulu, Haridra, Nimba"))) },
      { title: "Virechana & Basti in Gynaecological Conditions", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Shodhana (purificatory) procedures like Virechana and Basti are essential pre-treatments and primary therapies in gynaecological disorders. Virechana addresses Pitta-dominant conditions while Basti targets Vata-related pathologies."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Virechana — for Pittaja Yonivyapad, Asrigdara (menorrhagia), Rakta Pradara"), React.createElement("li", null, "• Niruha Basti — Dashamoola Kwatha for Vataja conditions, dysmenorrhoea"), React.createElement("li", null, "• Anuvasana Basti — Bala Taila, Dhanvantara Taila for Vata Anulomana"), React.createElement("li", null, "• Yoga Basti/Kala Basti protocols in chronic gynaecological disorders"))) },
      { title: "Panchakarma Protocol Planning in Stree Roga", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Systematic planning of Panchakarma in gynaecological practice requires understanding of menstrual cycle timing, Dosha assessment, and appropriate combination of Shodhana and Sthanika procedures."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Purvakarma: Snehana (internal oleation with Phala Ghrita) + Swedana"), React.createElement("li", null, "• Pradhana Karma timing: Virechana/Basti in Rituvyatita Kala; Uttara Basti in Ritukala"), React.createElement("li", null, "• Paschat Karma: Samsarjana Krama, Pathya-Apathya, follow-up"), React.createElement("li", null, "• Protocol for Vandhyatva: Shodhana → Uttara Basti → Shamana → conception attempt"))) },
    ],
    orientation: { why: "Panchakarma procedures are the cornerstone of Ayurvedic gynaecological management. Uttara Basti is the single most important therapeutic procedure for infertility and chronic gynaecological conditions. Understanding Sthanika Chikitsa (local therapies) is essential for clinical practice.", examWeight: "Very high-yield. Long answers on Uttara Basti Vidhi, Yoni Pichu/Varti/Dhupana, and Panchakarma protocol in Vandhyatva are frequently asked. Short notes on individual Sthanika procedures appear regularly." },
    definition: {
      ayurveda: `<p><strong>Panchakarma in Stree Roga</strong> refers to the systematic application of five purificatory procedures — particularly Vamana, Virechana, Basti (Niruha & Anuvasana), and Uttara Basti — in gynaecological disorders. Charaka Siddhi Sthana dedicates chapters 9 and 12 to Basti and Uttara Basti respectively.</p><p class="mt-2">Sthanika Chikitsa (local therapies) — Yoni Prakshalana, Pichu, Varti, and Dhupana — complement the Shodhana procedures and are unique to Ayurvedic gynaecology.</p>`,
      modern: `<p><strong>Modern parallels</strong> include intrauterine insemination (IUI), hysteroscopic procedures, vaginal medications (pessaries, creams), and uterine lavage. The concept of clearing the reproductive tract before conception attempts parallels Ayurvedic Shodhana before Garbhadhana.</p><p class="mt-2">Evidence for Uttara Basti's efficacy exists in tubal patency improvement, endometrial receptivity enhancement, and management of chronic pelvic inflammatory disease.</p>`,
    },
    shlokas: [
      { source: "Charaka Siddhi Sthana 12/15", devanagari: "योनिदोषहरं श्रेष्ठं वन्ध्यानां गर्भदं परम् |\nउत्तरबस्तिमाख्यातं सिद्धिस्थाने महर्षिणा ||", transliteration: "yonidoṣaharaṃ śreṣṭhaṃ vandhyānāṃ garbhadaṃ param |\nuttarabastimākhyātaṃ siddhisthāne maharṣiṇā ||", meaning: "Uttara Basti is the supreme therapy for curing Yoni Dosha (uterine disorders) and bestowing conception (Garbhada) in infertile women, as declared by the great sage in the Siddhi Sthana.", clinicalNote: "This shloka establishes Uttara Basti as the gold standard therapy in Ayurvedic infertility treatment. The word 'Garbhada' (conception-giving) indicates its primary role in Vandhyatva Chikitsa." },
      { source: "Charaka Siddhi Sthana 12/18", devanagari: "ऋतुकाले प्रदातव्यमुत्तरबस्तिमौषधम् |\nशुद्धायां योनौ बीजं हि क्षेत्रे शुद्धे प्ररोहति ||", transliteration: "ṛtukāle pradātavyamuttarabastimaauṣadham |\nśuddhāyāṃ yonau bījaṃ hi kṣetre śuddhe praorohati ||", meaning: "Uttara Basti should be administered during Ritukala (fertile period). Just as a seed germinates only in purified soil (Kshetra Shuddhi), conception occurs only in a cleansed uterus.", clinicalNote: "This beautifully illustrates the Kshetra-Bija concept (field-seed analogy). Uttara Basti timing in Ritukala (post-menstrual fertile phase) ensures optimal endometrial receptivity — akin to modern embryo transfer timing in IVF cycles." },
      { source: "Sushruta Chikitsa Sthana 37/25", devanagari: "प्रक्षालनं पिचुधारणमथ योनेः वर्तिर्धूपनम् |\nस्थानिकं कर्म योनीनां व्यापदेषु प्रशस्यते ||", transliteration: "prakṣālanaṃ picudhāraṇamatha yoneḥ vartirdhūpanam |\nsthānikaṃ karma yonīnāṃ vyāpadeṣu praśasyate ||", meaning: "Prakshalana (vaginal douche), Pichu Dharana (tampon placement), Varti (suppository), and Dhupana (fumigation) — these Sthanika Karmas are recommended in Yonivyapad (gynaecological disorders).", clinicalNote: "This shloka enumerates the four Sthanika Chikitsa procedures that form the local therapy protocol in Ayurvedic gynaecology. These are often combined with systemic Shodhana for comprehensive management." },
      { source: "Charaka Siddhi Sthana 1/40", devanagari: "बस्तिकर्म विशेषेण वातव्याधिहरं परम् |\nअर्धचिकित्सा बस्तिश्च केचिदाहुश्चिकित्सिते ||", transliteration: "bastikarma viśeṣeṇa vātavyādhiharaṃ param |\nardhacikitsā bastiśca kecidāhuścikitsite ||", meaning: "Basti Karma is the supreme therapy for Vata disorders. Some authorities declare Basti itself as half of the entire treatment (Ardha Chikitsa).", clinicalNote: "Since most gynaecological disorders involve Apana Vayu Dushti, Basti holds a central place in Stree Roga management. The concept of Basti as Ardha Chikitsa underscores its therapeutic supremacy." },
    ],
    dualCols: [
      { title: "Uttara Basti vs Modern Intrauterine Procedures", ayurvedaTitle: "Uttara Basti (Ayurveda)", modernTitle: "Intrauterine Procedures (Modern)", ayurvedaContent: `<p><strong>Uttara Basti Vidhi:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Purvakarma:</strong> Snehana-Swedana, local Yoni Prakshalana</li><li><strong>Yantra:</strong> Pushpa Netra (intrauterine cannula) — 10 Angula length</li><li><strong>Matra:</strong> Sneha — 2 Pala; Kashaya — 4 Pala</li><li><strong>Kala:</strong> Ritukala (post-menstrual fertile phase)</li><li><strong>Duration:</strong> 3 consecutive days or alternating days for 6 sessions</li><li><strong>Drugs:</strong> Phala Ghrita, Shatapushpa Taila, Dashamoola Kwatha</li></ul>`, modernContent: `<p><strong>Modern Intrauterine Procedures:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>IUI:</strong> Washed sperm placed intrauterine, timed with ovulation</li><li><strong>HSG:</strong> Contrast dye through uterus for tubal patency assessment</li><li><strong>Hysteroscopy:</strong> Direct visualization and treatment of intrauterine pathology</li><li><strong>Embryo Transfer:</strong> IVF embryo placement at Day 3 or Day 5 (blastocyst)</li><li><strong>Endometrial biopsy:</strong> Assessment of secretory changes and receptivity</li></ul><p class="mt-2">Note: Uttara Basti may improve tubal patency (similar to HSG therapeutic effect) and endometrial receptivity.</p>` },
    ],
    clinicalFeatures: [{ title: "Sthanika Chikitsa — Procedures & Indications", headers: ["Procedure", "Method", "Common Drugs", "Indications"], rows: [["<strong>Yoni Prakshalana</strong>", "Vaginal douche with Kashaya", "Panchavalkala, Triphala, Dashamoola", "Yoni Kandu, Shweta Pradara, pre-Uttara Basti"], ["<strong>Yoni Pichu</strong>", "Medicated oil-soaked tampon in vaginal canal", "Jatyadi Taila, Phala Ghrita, Shatapushpa Taila", "Cervical erosion, Vaginitis, Vandhyatva"], ["<strong>Yoni Varti</strong>", "Medicated suppository inserted per vaginam", "Dashamoola, Palasha, Apamarga Varti", "Yonivyapad, chronic discharge, infections"], ["<strong>Yoni Dhupana</strong>", "Vaginal fumigation with medicated smoke", "Guggulu, Haridra, Nimba, Ghrita", "Yoni Kandu, recurrent infections, post-Shodhana"], ["<strong>Uttara Basti</strong>", "Intrauterine instillation via Pushpa Netra", "Phala Ghrita, Shatapushpa Taila, Dashamoola", "Vandhyatva, Artava Vyapad, tubal block"]] }],
    investigations: [{ title: "Pre-Panchakarma Assessment in Stree Roga", headers: ["Assessment", "Purpose", "When to Perform"], rows: [["<strong>Prakriti & Dosha Pariksha</strong>", "Determine constitution and current Dosha vitiation", "Before planning any Shodhana"], ["<strong>Agni Pariksha</strong>", "Assess digestive capacity for Snehapana tolerance", "Before Purvakarma"], ["<strong>Artava Pariksha</strong>", "Determine menstrual status and cycle day", "To time Uttara Basti in Ritukala"], ["<strong>Pelvic USG</strong>", "Rule out PID, endometriosis, structural anomalies", "Before any intrauterine procedure"], ["<strong>HSG / Sonosalpingography</strong>", "Tubal patency assessment", "Before Uttara Basti for infertility — baseline comparison"]] }],
    management: {
      diagramTitle: "Panchakarma Protocol in Vandhyatva (Infertility)",
      diagramSvg: `<svg viewBox="0 0 800 450" xmlns="http://www.w3.org/2000/svg" class="w-full max-w-3xl"><style>.box{fill:#FFF8E1;stroke:#C8712A;stroke-width:2;rx:10}.box-blue{fill:#E3F2FD;stroke:#42A5F5;stroke-width:2;rx:10}.box-green{fill:#E8F5E9;stroke:#66BB6A;stroke-width:2;rx:10}.box-pink{fill:#FCE4EC;stroke:#EC407A;stroke-width:2;rx:10}.label{font-family:'DM Sans',sans-serif;font-size:12px;fill:#333;text-anchor:middle}.label-bold{font-family:'DM Sans',sans-serif;font-size:13px;fill:#333;font-weight:bold;text-anchor:middle}.arrow{stroke:#C8712A;stroke-width:2;fill:none;marker-end:url(#ah30)}.small{font-size:11px}</style><defs><marker id="ah30" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto"><polygon points="0 0,10 3.5,0 7" fill="#C8712A"/></marker></defs><rect class="box" x="250" y="10" width="300" height="40"/><text class="label-bold" x="400" y="35">Vandhyatva (Infertility) Patient</text><line class="arrow" x1="400" y1="50" x2="400" y2="80"/><rect class="box-blue" x="200" y="80" width="400" height="45"/><text class="label-bold" x="400" y="100">Step 1: Purvakarma</text><text class="label small" x="400" y="117">Snehapana (Phala Ghrita × 7 days) → Abhyanga → Swedana</text><line class="arrow" x1="400" y1="125" x2="400" y2="155"/><rect class="box-pink" x="200" y="155" width="400" height="45"/><text class="label-bold" x="400" y="175">Step 2: Shodhana (Rituvyatita Kala)</text><text class="label small" x="400" y="192">Virechana (Pittaja) or Basti (Vataja) as indicated</text><line class="arrow" x1="400" y1="200" x2="400" y2="230"/><rect class="box-green" x="200" y="230" width="400" height="45"/><text class="label-bold" x="400" y="250">Step 3: Uttara Basti (Ritukala — Post-menstrual)</text><text class="label small" x="400" y="267">Phala Ghrita / Shatapushpa Taila × 3-6 sessions</text><line class="arrow" x1="400" y1="275" x2="400" y2="305"/><rect class="box" x="200" y="305" width="400" height="45"/><text class="label-bold" x="400" y="325">Step 4: Shamana Yoga + Ritucharyya</text><text class="label small" x="400" y="342">Phala Ghrita orally, Pushpadhanva Rasa, conception attempt</text><line class="arrow" x1="400" y1="350" x2="400" y2="385"/><rect class="box-green" x="250" y="385" width="300" height="45"/><text class="label-bold" x="400" y="405">Outcome: Garbha Sthapana</text><text class="label small" x="400" y="422">Kshetra Shuddhi → Bija Sthapana → Garbha</text></svg>`,
      notes: `<p><strong>Key points:</strong></p><ul class="list-disc pl-5 mt-2 space-y-1"><li>Uttara Basti is the most important procedure for Vandhyatva — termed 'Garbhada' by Charaka</li><li>Timing is critical: Shodhana in Rituvyatita Kala (post-ovulatory), Uttara Basti in Ritukala (fertile phase)</li><li>Phala Ghrita is the drug of choice for both Snehapana and Uttara Basti in infertility</li><li>Yoni Prakshalana precedes all vaginal/intrauterine procedures (like pre-op antiseptic wash)</li><li>Basti is Ardha Chikitsa — forms the backbone of Vata management in gynaecological disorders</li></ul>`,
    },
    integration: `<h3 class="font-heading text-xl font-semibold text-saffron-800 mb-3">Panchakarma in Stree Roga — Ayurveda-Modern Integration</h3><div class="space-y-4"><p>Panchakarma procedures in gynaecology represent a sophisticated system of local and systemic purification aimed at optimizing reproductive function. Uttara Basti parallels modern intrauterine procedures, Sthanika Chikitsa aligns with vaginal drug delivery systems, and Shodhana pre-treatment mirrors the concept of endometrial priming in ART cycles.</p><div class="bg-white/60 p-4 rounded-lg mt-4"><h4 class="font-semibold text-gray-800 mb-2">Clinical Protocol</h4><ol class="list-decimal pl-5 space-y-1 text-sm"><li>Dosha assessment and selection of appropriate Shodhana (Virechana for Pitta, Basti for Vata)</li><li>Purvakarma: Snehapana with Phala Ghrita + Abhyanga + Swedana</li><li>Shodhana in appropriate menstrual cycle phase (post-menstrual for Virechana)</li><li>Sthanika Chikitsa: Yoni Prakshalana → Pichu/Varti → Uttara Basti sequence</li><li>Follow-up: Shamana drugs, conception counselling, pelvic USG for response assessment</li></ol></div></div>`,
    examBullets: [
      "Uttara Basti is the most important Panchakarma for Vandhyatva — called 'Garbhada' (Charaka Siddhi 12).",
      "Uttara Basti timing: administer during Ritukala (post-menstrual fertile phase) for best results.",
      "Uttara Basti Yantra: Pushpa Netra — 10 Angula length intrauterine cannula.",
      "Uttara Basti Matra: Sneha — 2 Pala; Kashaya — 4 Pala (Charaka Siddhi 12).",
      "Phala Ghrita is the drug of choice for Uttara Basti and Snehapana in infertility management.",
      "Sthanika Chikitsa: Yoni Prakshalana (douche), Pichu (tampon), Varti (suppository), Dhupana (fumigation).",
      "Yoni Prakshalana with Panchavalkala Kashaya is done before all intrauterine procedures.",
      "Yoni Pichu with Jatyadi Taila — for cervical erosion and chronic vaginitis.",
      "Basti is Ardha Chikitsa (half of all treatment) — especially important for Vata-dominant gynaecological disorders.",
      "Virechana is indicated in Pittaja Yonivyapad, Asrigdara, and Rakta Pradara.",
      "Yoga Basti: 8 Bastis (5 Anuvasana + 3 Niruha); Kala Basti: 16 Bastis; Karma Basti: 30 Bastis.",
      "Kshetra-Bija concept: Shodhana purifies the Kshetra (uterus/field) for Bija (seed/conception) to succeed.",
      "Purvakarma for Uttara Basti: Snehapana → Abhyanga → Swedana → Yoni Prakshalana.",
      "Shatapushpa Taila and Shatavari Ghrita are commonly used for Uttara Basti in infertility.",
      "Contraindications of Uttara Basti: active PID, pregnancy, menstruation, cervical malignancy.",
    ],
    mnemonics: [
      { title: "Sthanika Chikitsa (4 Local Therapies)", acronym: "PPVD", expansions: ["Prakshalana (vaginal douche)", "Pichu (medicated tampon)", "Varti (vaginal suppository)", "Dhupana (vaginal fumigation)"] },
      { title: "Uttara Basti Drug Protocol", acronym: "PSDS", expansions: ["Phala Ghrita (Sneha UB for infertility)", "Shatapushpa Taila (Sneha UB for Artava disorders)", "Dashamoola Kwatha (Kashaya UB for Vataja conditions)", "Shatavari Ghrita (Sneha UB for uterine nourishment)"] },
      { title: "Vandhyatva Panchakarma Sequence", acronym: "SPUS", expansions: ["Snehapana-Swedana (Purvakarma)", "Purification — Virechana/Basti (Shodhana)", "Uttara Basti (Pradhana Karma — Ritukala)", "Shamana + conception attempt (Paschat Karma)"] },
      { title: "Basti Types in Gynae", acronym: "YANK", expansions: ["Yoga Basti — 8 Bastis (short course)", "Anuvasana Basti — oil Basti (Vata Shamana)", "Niruha Basti — decoction Basti (Shodhana)", "Karma Basti — 30 Bastis (full course)"] },
    ],
  };
}
