import React from "react";
export function getM31Content() {
  return {
    references: ["Charaka Vimana Sthana Ch. 8 (Rogabhishak Jitiya)", "Sushruta Sutra Sthana Ch. 4", "Ashtanga Hridaya Sutra Sthana Ch. 1", "CCRAS Guidelines for Clinical Research in Ayurveda", "Park's Textbook of Preventive & Social Medicine", "Mahajan's Methods in Biostatistics (8th Ed.)"],
    units: [
      { title: "Research Methodology in Ayurveda", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Research methodology (Anusandhana Paddhati) in Ayurveda integrates classical Pramana (means of valid knowledge) with modern research design principles. Understanding study designs, formulating research questions, and applying evidence-based methods to Ayurvedic practice is essential."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Pramana — Pratyaksha (direct observation), Anumana (inference), Aptopadesha (authoritative testimony), Yukti (reasoning)"), React.createElement("li", null, "• Types of research: fundamental, drug, clinical, literary, survey-based"), React.createElement("li", null, "• Study designs: RCT, cohort, case-control, cross-sectional, case series"), React.createElement("li", null, "• Hypothesis formulation: null hypothesis (H0) and alternative hypothesis (H1)"))) },
      { title: "Biostatistics — Measures & Tests", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Biostatistics provides the mathematical framework for analysing research data. Understanding measures of central tendency, dispersion, and statistical tests is critical for interpreting and publishing research."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Central tendency: Mean, Median, Mode"), React.createElement("li", null, "• Dispersion: Standard Deviation (SD), Variance, Range, SEM"), React.createElement("li", null, "• Significance: p-value (<0.05), confidence interval (95% CI)"), React.createElement("li", null, "• Tests: Chi-square (categorical), t-test (means), ANOVA (>2 groups), Mann-Whitney (non-parametric)"))) },
      { title: "Ethics, Consent & CTRI Registration", content: React.createElement("div", null, React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Ethical conduct in research includes informed consent, IEC (Institutional Ethics Committee) approval, CTRI (Clinical Trials Registry — India) registration, and adherence to ICMR guidelines. Ayurvedic research must follow GCP (Good Clinical Practice) norms."), React.createElement("ul", { className: "mt-3 space-y-2 text-sm text-gray-600" }, React.createElement("li", null, "• Informed consent: voluntary, competent, complete information, written documentation"), React.createElement("li", null, "• IEC/IRB approval: mandatory before study initiation"), React.createElement("li", null, "• CTRI registration: mandatory for all clinical trials in India since 2017"), React.createElement("li", null, "• Declaration of Helsinki, Belmont Report, ICMR Ethical Guidelines 2017"))) },
    ],
    orientation: { why: "Anusandhana Paddhati (Research Methodology) is essential for validating Ayurvedic treatments through evidence-based research. BAMS graduates must understand study designs, biostatistics, and ethical frameworks to conduct and critically appraise clinical research — especially in Stree Roga and Prasuti Tantra.", examWeight: "Moderate yield. Short notes on study designs, p-value, chi-square test, informed consent, and CTRI registration are common. Long answers on research protocol design for Ayurvedic clinical trials appear occasionally." },
    definition: {
      ayurveda: `<p><strong>Anusandhana</strong> (research) in Ayurveda is rooted in the concept of Pramana — valid means of knowledge acquisition. Charaka Vimana Sthana 8 describes the fourfold Pramana: Pratyaksha (direct perception), Anumana (inference), Aptopadesha (authoritative testimony), and Yukti (experimental reasoning).</p><p class="mt-2">Yukti Pramana is considered most relevant to clinical research as it involves systematic observation, reasoning, and validation — closely paralleling the modern scientific method.</p>`,
      modern: `<p><strong>Research Methodology & Biostatistics</strong> encompasses the systematic approach to designing studies, collecting data, analysing results, and drawing valid conclusions. The hierarchy of evidence places:<br/><strong>Systematic Reviews/Meta-analyses</strong> at the top, followed by <strong>RCTs</strong>, Cohort studies, Case-control studies, Case series, and Expert opinion.</p><p class="mt-2">Biostatistics provides tools for descriptive analysis (mean, SD) and inferential analysis (t-test, chi-square, ANOVA) to determine statistical significance (p<0.05).</p>`,
    },
    shlokas: [
      { source: "Charaka Vimana Sthana 8/27", devanagari: "प्रत्यक्षमनुमानं च आप्तोपदेशश्च युक्तिश्च |\nचतुर्विधं प्रमाणं तु परीक्षार्थं प्रकीर्तितम् ||", transliteration: "pratyakṣamanumānaṃ ca āptopadeśaśca yuktiśca |\ncaturvidhaṃ pramāṇaṃ tu parīkṣārthaṃ prakīrtitam ||", meaning: "The fourfold means of valid knowledge (Pramana) are: Pratyaksha (direct perception), Anumana (inference), Aptopadesha (authoritative testimony), and Yukti (experimental reasoning) — these are declared for the purpose of examination and investigation.", clinicalNote: "This shloka forms the epistemological foundation of Ayurvedic research. Pratyaksha parallels clinical observation, Anumana parallels logical deduction, Aptopadesha parallels evidence from classical texts, and Yukti parallels experimental/clinical research methodology." },
      { source: "Charaka Sutra Sthana 11/17", devanagari: "परीक्ष्यकारिणो हि कुशला भवन्ति |\nन अपरीक्ष्यकारिणः कदाचन सिद्धिमाप्नुवन्ति ||", transliteration: "parīkṣyakāriṇo hi kuśalā bhavanti |\nna aparīkṣyakāriṇaḥ kadācana siddhimāpnuvanti ||", meaning: "Those who act after thorough examination (Pariksha) become skilful. Those who act without examination never achieve success.", clinicalNote: "This emphasizes evidence-based practice — a physician must examine, investigate, and validate before treating. This principle directly supports the need for clinical research and systematic data collection in Ayurvedic practice." },
      { source: "Charaka Vimana Sthana 8/3", devanagari: "युक्तिः प्रमाणं यत्नेन बुद्ध्या चाऽन्वीक्षते भिषक् |\nहेतुफलं समीक्ष्यैव कर्म कुर्यात् विचक्षणः ||", transliteration: "yuktiḥ pramāṇaṃ yatnena buddhyā cā'nvīkṣate bhiṣak |\nhetuphalṃ samīkṣyaiva karma kuryāt vicakṣaṇaḥ ||", meaning: "The wise physician uses Yukti Pramana (rational/experimental reasoning) and examines cause and effect (Hetu-Phala) through intellect and effort before undertaking treatment.", clinicalNote: "Yukti Pramana is the Ayurvedic equivalent of experimental science. The Hetu-Phala (cause-effect) analysis parallels the modern hypothesis-testing approach in clinical trials — observe, hypothesize, experiment, conclude." },
    ],
    dualCols: [
      { title: "Research Framework — Ayurveda vs Modern", ayurvedaTitle: "Pramana (Ayurvedic Epistemology)", modernTitle: "Modern Research Methodology", ayurvedaContent: `<p><strong>Chatushpada Pramana:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Pratyaksha:</strong> Direct clinical observation — patient examination, Rogi Pariksha</li><li><strong>Anumana:</strong> Inference from signs — Nidana Panchaka (5 diagnostic tools)</li><li><strong>Aptopadesha:</strong> Classical textual evidence — Samhita references (systematic review parallel)</li><li><strong>Yukti:</strong> Experimental reasoning — clinical trial, cause-effect analysis</li></ul><p class="mt-2">Trividha Pariksha (Darshana, Sparshana, Prashna) = clinical examination protocol</p>`, modernContent: `<p><strong>Evidence Hierarchy:</strong></p><ul class="list-disc pl-4 space-y-1"><li><strong>Level I:</strong> Systematic reviews & meta-analyses</li><li><strong>Level II:</strong> Randomized Controlled Trials (RCTs)</li><li><strong>Level III:</strong> Cohort studies (prospective/retrospective)</li><li><strong>Level IV:</strong> Case-control studies</li><li><strong>Level V:</strong> Case series, case reports, expert opinion</li></ul><p class="mt-2">PICO framework: Population, Intervention, Comparison, Outcome</p>` },
    ],
    clinicalFeatures: [{ title: "Study Designs — Types & Characteristics", headers: ["Study Design", "Type", "Key Feature", "Use in Ayurvedic Research"], rows: [["<strong>RCT</strong>", "Interventional (experimental)", "Randomization + control group + blinding", "Drug efficacy trials (e.g., Shatavari in oligomenorrhea)"], ["<strong>Cohort Study</strong>", "Observational (analytical)", "Follows exposed vs unexposed groups over time", "Long-term effects of Panchakarma, Rasayana studies"], ["<strong>Case-Control</strong>", "Observational (analytical)", "Compares cases with disease to controls without", "Risk factors for Yonivyapad, PCOS in Ayurveda"], ["<strong>Cross-sectional</strong>", "Observational (descriptive)", "Snapshot at one point in time (prevalence)", "Prevalence of Prakriti types in gynaecological disorders"], ["<strong>Case Series / Report</strong>", "Descriptive", "Detailed report of individual cases", "Novel Ayurvedic treatment outcomes, rare conditions"]] }],
    investigations: [{ title: "Biostatistical Tests — Selection Guide", headers: ["Statistical Test", "Data Type", "When to Use", "Example"], rows: [["<strong>Chi-square test (χ²)</strong>", "Categorical (nominal)", "Compare proportions between groups", "Cure rate: Ayurvedic vs modern treatment"], ["<strong>Student's t-test</strong>", "Continuous (parametric)", "Compare means of 2 groups", "Mean pain score before vs after Uttara Basti"], ["<strong>Paired t-test</strong>", "Continuous (parametric)", "Same group, before vs after", "Hb level pre- and post-treatment in Pandu"], ["<strong>ANOVA</strong>", "Continuous (parametric)", "Compare means of >2 groups", "Comparing 3 treatment groups in dysmenorrhea"], ["<strong>Mann-Whitney U</strong>", "Ordinal/non-parametric", "Compare 2 groups, non-normal data", "Symptom grading scores (mild/moderate/severe)"]] }],
    management: {
      diagramTitle: "Clinical Research Protocol Design — Flowchart",
      diagramSvg: `<svg viewBox="0 0 800 480" xmlns="http://www.w3.org/2000/svg" class="w-full max-w-3xl"><style>.box{fill:#FFF8E1;stroke:#C8712A;stroke-width:2;rx:10}.box-blue{fill:#E3F2FD;stroke:#42A5F5;stroke-width:2;rx:10}.box-green{fill:#E8F5E9;stroke:#66BB6A;stroke-width:2;rx:10}.box-red{fill:#FFEBEE;stroke:#EF5350;stroke-width:2;rx:10}.label{font-family:'DM Sans',sans-serif;font-size:12px;fill:#333;text-anchor:middle}.label-bold{font-family:'DM Sans',sans-serif;font-size:13px;fill:#333;font-weight:bold;text-anchor:middle}.arrow{stroke:#C8712A;stroke-width:2;fill:none;marker-end:url(#ah31)}.small{font-size:11px}</style><defs><marker id="ah31" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto"><polygon points="0 0,10 3.5,0 7" fill="#C8712A"/></marker></defs><rect class="box" x="250" y="10" width="300" height="40"/><text class="label-bold" x="400" y="35">Research Question (PICO)</text><line class="arrow" x1="400" y1="50" x2="400" y2="75"/><rect class="box-blue" x="250" y="75" width="300" height="40"/><text class="label-bold" x="400" y="100">Literature Review (Aptopadesha)</text><line class="arrow" x1="400" y1="115" x2="400" y2="140"/><rect class="box" x="250" y="140" width="300" height="40"/><text class="label-bold" x="400" y="165">Study Design Selection (RCT/Cohort)</text><line class="arrow" x1="400" y1="180" x2="400" y2="205"/><rect class="box-red" x="230" y="205" width="340" height="40"/><text class="label-bold" x="400" y="230">IEC Approval + CTRI Registration</text><line class="arrow" x1="400" y1="245" x2="400" y2="270"/><rect class="box-green" x="230" y="270" width="340" height="45"/><text class="label-bold" x="400" y="290">Data Collection (Yukti Pramana)</text><text class="label small" x="400" y="305">Informed consent → Sampling → Intervention</text><line class="arrow" x1="400" y1="315" x2="400" y2="340"/><rect class="box-blue" x="230" y="340" width="340" height="45"/><text class="label-bold" x="400" y="360">Statistical Analysis</text><text class="label small" x="400" y="375">Descriptive (Mean/SD) + Inferential (t-test/χ²)</text><line class="arrow" x1="400" y1="385" x2="400" y2="415"/><rect class="box-green" x="220" y="415" width="360" height="45"/><text class="label-bold" x="400" y="435">Results, Discussion & Publication</text><text class="label small" x="400" y="452">p-value interpretation, clinical significance, CONSORT</text></svg>`,
      notes: `<p><strong>Key points:</strong></p><ul class="list-disc pl-5 mt-2 space-y-1"><li>CTRI registration is mandatory for all clinical trials in India since 2017</li><li>Informed consent must be voluntary, informed, competent, and documented in writing</li><li>p-value <0.05 means <5% probability that the result occurred by chance (statistically significant)</li><li>RCT is the gold standard for establishing treatment efficacy in Ayurvedic drug trials</li><li>CONSORT guidelines should be followed for reporting RCTs; STROBE for observational studies</li></ul>`,
    },
    integration: `<h3 class="font-heading text-xl font-semibold text-saffron-800 mb-3">Anusandhana Paddhati — Ayurveda-Modern Integration</h3><div class="space-y-4"><p>Integrating Ayurvedic Pramana with modern research methodology creates a robust framework for evidence-based Ayurvedic practice. Yukti Pramana aligns with the experimental method; Aptopadesha provides the classical evidence base akin to systematic reviews; and Pratyaksha forms the clinical observation foundation.</p><div class="bg-white/60 p-4 rounded-lg mt-4"><h4 class="font-semibold text-gray-800 mb-2">Research Protocol for Stree Roga</h4><ol class="list-decimal pl-5 space-y-1 text-sm"><li>Formulate PICO question with Ayurvedic and modern outcome measures</li><li>Design RCT with Ayurvedic assessment criteria (Dosha, Agni, Srotas) alongside modern parameters</li><li>Obtain IEC approval, CTRI registration, and informed consent</li><li>Collect data using validated assessment tools and subjective Ayurvedic grading</li><li>Analyse with appropriate statistical tests, report per CONSORT/STROBE guidelines</li></ol></div></div>`,
    examBullets: [
      "Chatushpada Pramana: Pratyaksha (observation), Anumana (inference), Aptopadesha (authority), Yukti (reasoning) — Charaka Vimana 8.",
      "Yukti Pramana is the Ayurvedic equivalent of experimental research methodology — Hetu-Phala (cause-effect) analysis.",
      "RCT (Randomized Controlled Trial) is the gold standard for evaluating treatment efficacy.",
      "PICO framework: Population, Intervention, Comparison, Outcome — essential for framing research questions.",
      "Null hypothesis (H0): no significant difference between groups; Alternative hypothesis (H1): significant difference exists.",
      "p-value <0.05 = statistically significant (less than 5% probability of result occurring by chance).",
      "Type I error (alpha): rejecting true H0 (false positive). Type II error (beta): accepting false H0 (false negative).",
      "Chi-square test: for categorical data (comparing proportions). t-test: for continuous data (comparing means).",
      "Paired t-test: same group before and after treatment. Unpaired t-test: two different groups.",
      "Standard Deviation (SD) measures data spread; Standard Error of Mean (SEM) measures precision of sample mean.",
      "CTRI (Clinical Trials Registry — India): mandatory registration for all clinical trials in India since 2017.",
      "Informed consent: must be voluntary, informed (complete disclosure), competent (patient able to decide), and documented.",
      "IEC (Institutional Ethics Committee) approval: mandatory before initiating any human research.",
      "CONSORT guidelines: for reporting RCTs; STROBE: for observational studies; PRISMA: for systematic reviews.",
      "Sampling methods: simple random, stratified, systematic, convenience — random sampling reduces selection bias.",
    ],
    mnemonics: [
      { title: "Pramana (4 Means of Knowledge)", acronym: "PAAY", expansions: ["Pratyaksha (direct perception/observation)", "Anumana (inference/logical deduction)", "Aptopadesha (authoritative testimony/textual evidence)", "Yukti (experimental reasoning/research)"] },
      { title: "Research Ethics Essentials", acronym: "VICE", expansions: ["Voluntary informed consent", "IEC/IRB approval before study", "CTRI registration (mandatory since 2017)", "Ethical guidelines — ICMR, Declaration of Helsinki"] },
      { title: "Statistical Tests Selection", acronym: "CAMP", expansions: ["Chi-square — categorical data (proportions)", "ANOVA — >2 group means comparison", "Mann-Whitney — non-parametric (ordinal data)", "Paired t-test — same group, before vs after"] },
      { title: "Evidence Hierarchy (Top to Bottom)", acronym: "SRCCE", expansions: ["Systematic Review / Meta-analysis (Level I)", "RCT — Randomized Controlled Trial (Level II)", "Cohort study (Level III)", "Case-Control study (Level IV)", "Expert opinion / Case series (Level V)"] },
    ],
  };
}
