//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  topic: Topic;
  topicConnection: TopicConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTopicArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTopicConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TopicFilter>;
};

export type DocumentFilter = {
  topic?: InputMaybe<TopicFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Topic | Folder;

export type TopicOrientation = {
  __typename?: 'TopicOrientation';
  why?: Maybe<Scalars['String']['output']>;
  examWeight?: Maybe<Scalars['String']['output']>;
};

export type TopicDefinition = {
  __typename?: 'TopicDefinition';
  ayurveda?: Maybe<Scalars['JSON']['output']>;
  modern?: Maybe<Scalars['JSON']['output']>;
};

export type TopicShlokas = {
  __typename?: 'TopicShlokas';
  source: Scalars['String']['output'];
  devanagari: Scalars['String']['output'];
  transliteration: Scalars['String']['output'];
  meaning: Scalars['String']['output'];
  clinicalNote?: Maybe<Scalars['String']['output']>;
};

export type TopicDualCols = {
  __typename?: 'TopicDualCols';
  title: Scalars['String']['output'];
  ayurvedaContent?: Maybe<Scalars['JSON']['output']>;
  modernContent?: Maybe<Scalars['JSON']['output']>;
};

export type TopicMnemonics = {
  __typename?: 'TopicMnemonics';
  title: Scalars['String']['output'];
  acronym: Scalars['String']['output'];
  expansions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Topic = Node & Document & {
  __typename?: 'Topic';
  moduleNumber: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  nameAyurveda: Scalars['String']['output'];
  nameDevanagari: Scalars['String']['output'];
  nameEnglish: Scalars['String']['output'];
  paper: Scalars['Float']['output'];
  semester: Scalars['Float']['output'];
  units: Scalars['Float']['output'];
  category: Scalars['String']['output'];
  references?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  orientation?: Maybe<TopicOrientation>;
  definition?: Maybe<TopicDefinition>;
  shlokas?: Maybe<Array<Maybe<TopicShlokas>>>;
  dualCols?: Maybe<Array<Maybe<TopicDualCols>>>;
  examBullets?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  mnemonics?: Maybe<Array<Maybe<TopicMnemonics>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TopicOrientationFilter = {
  why?: InputMaybe<StringFilter>;
  examWeight?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TopicDefinitionFilter = {
  ayurveda?: InputMaybe<RichTextFilter>;
  modern?: InputMaybe<RichTextFilter>;
};

export type TopicShlokasFilter = {
  source?: InputMaybe<StringFilter>;
  devanagari?: InputMaybe<StringFilter>;
  transliteration?: InputMaybe<StringFilter>;
  meaning?: InputMaybe<StringFilter>;
  clinicalNote?: InputMaybe<StringFilter>;
};

export type TopicDualColsFilter = {
  title?: InputMaybe<StringFilter>;
  ayurvedaContent?: InputMaybe<RichTextFilter>;
  modernContent?: InputMaybe<RichTextFilter>;
};

export type TopicMnemonicsFilter = {
  title?: InputMaybe<StringFilter>;
  acronym?: InputMaybe<StringFilter>;
  expansions?: InputMaybe<StringFilter>;
};

export type TopicFilter = {
  moduleNumber?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  nameAyurveda?: InputMaybe<StringFilter>;
  nameDevanagari?: InputMaybe<StringFilter>;
  nameEnglish?: InputMaybe<StringFilter>;
  paper?: InputMaybe<NumberFilter>;
  semester?: InputMaybe<NumberFilter>;
  units?: InputMaybe<NumberFilter>;
  category?: InputMaybe<StringFilter>;
  references?: InputMaybe<StringFilter>;
  orientation?: InputMaybe<TopicOrientationFilter>;
  definition?: InputMaybe<TopicDefinitionFilter>;
  shlokas?: InputMaybe<TopicShlokasFilter>;
  dualCols?: InputMaybe<TopicDualColsFilter>;
  examBullets?: InputMaybe<StringFilter>;
  mnemonics?: InputMaybe<TopicMnemonicsFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TopicConnectionEdges = {
  __typename?: 'TopicConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Topic>;
};

export type TopicConnection = Connection & {
  __typename?: 'TopicConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TopicConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTopic: Topic;
  createTopic: Topic;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTopicArgs = {
  relativePath: Scalars['String']['input'];
  params: TopicMutation;
};


export type MutationCreateTopicArgs = {
  relativePath: Scalars['String']['input'];
  params: TopicMutation;
};

export type DocumentUpdateMutation = {
  topic?: InputMaybe<TopicMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  topic?: InputMaybe<TopicMutation>;
};

export type TopicOrientationMutation = {
  why?: InputMaybe<Scalars['String']['input']>;
  examWeight?: InputMaybe<Scalars['String']['input']>;
};

export type TopicDefinitionMutation = {
  ayurveda?: InputMaybe<Scalars['JSON']['input']>;
  modern?: InputMaybe<Scalars['JSON']['input']>;
};

export type TopicShlokasMutation = {
  source?: InputMaybe<Scalars['String']['input']>;
  devanagari?: InputMaybe<Scalars['String']['input']>;
  transliteration?: InputMaybe<Scalars['String']['input']>;
  meaning?: InputMaybe<Scalars['String']['input']>;
  clinicalNote?: InputMaybe<Scalars['String']['input']>;
};

export type TopicDualColsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  ayurvedaContent?: InputMaybe<Scalars['JSON']['input']>;
  modernContent?: InputMaybe<Scalars['JSON']['input']>;
};

export type TopicMnemonicsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  acronym?: InputMaybe<Scalars['String']['input']>;
  expansions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TopicMutation = {
  moduleNumber?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  nameAyurveda?: InputMaybe<Scalars['String']['input']>;
  nameDevanagari?: InputMaybe<Scalars['String']['input']>;
  nameEnglish?: InputMaybe<Scalars['String']['input']>;
  paper?: InputMaybe<Scalars['Float']['input']>;
  semester?: InputMaybe<Scalars['Float']['input']>;
  units?: InputMaybe<Scalars['Float']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  references?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  orientation?: InputMaybe<TopicOrientationMutation>;
  definition?: InputMaybe<TopicDefinitionMutation>;
  shlokas?: InputMaybe<Array<InputMaybe<TopicShlokasMutation>>>;
  dualCols?: InputMaybe<Array<InputMaybe<TopicDualColsMutation>>>;
  examBullets?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  mnemonics?: InputMaybe<Array<InputMaybe<TopicMnemonicsMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TopicPartsFragment = { __typename: 'Topic', moduleNumber: string, slug: string, nameAyurveda: string, nameDevanagari: string, nameEnglish: string, paper: number, semester: number, units: number, category: string, references?: Array<string | null> | null, examBullets?: Array<string | null> | null, body?: any | null, orientation?: { __typename: 'TopicOrientation', why?: string | null, examWeight?: string | null } | null, definition?: { __typename: 'TopicDefinition', ayurveda?: any | null, modern?: any | null } | null, shlokas?: Array<{ __typename: 'TopicShlokas', source: string, devanagari: string, transliteration: string, meaning: string, clinicalNote?: string | null } | null> | null, dualCols?: Array<{ __typename: 'TopicDualCols', title: string, ayurvedaContent?: any | null, modernContent?: any | null } | null> | null, mnemonics?: Array<{ __typename: 'TopicMnemonics', title: string, acronym: string, expansions?: Array<string | null> | null } | null> | null };

export type TopicQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TopicQuery = { __typename?: 'Query', topic: { __typename: 'Topic', id: string, moduleNumber: string, slug: string, nameAyurveda: string, nameDevanagari: string, nameEnglish: string, paper: number, semester: number, units: number, category: string, references?: Array<string | null> | null, examBullets?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, orientation?: { __typename: 'TopicOrientation', why?: string | null, examWeight?: string | null } | null, definition?: { __typename: 'TopicDefinition', ayurveda?: any | null, modern?: any | null } | null, shlokas?: Array<{ __typename: 'TopicShlokas', source: string, devanagari: string, transliteration: string, meaning: string, clinicalNote?: string | null } | null> | null, dualCols?: Array<{ __typename: 'TopicDualCols', title: string, ayurvedaContent?: any | null, modernContent?: any | null } | null> | null, mnemonics?: Array<{ __typename: 'TopicMnemonics', title: string, acronym: string, expansions?: Array<string | null> | null } | null> | null } };

export type TopicConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TopicFilter>;
}>;


export type TopicConnectionQuery = { __typename?: 'Query', topicConnection: { __typename?: 'TopicConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TopicConnectionEdges', cursor: string, node?: { __typename: 'Topic', id: string, moduleNumber: string, slug: string, nameAyurveda: string, nameDevanagari: string, nameEnglish: string, paper: number, semester: number, units: number, category: string, references?: Array<string | null> | null, examBullets?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, orientation?: { __typename: 'TopicOrientation', why?: string | null, examWeight?: string | null } | null, definition?: { __typename: 'TopicDefinition', ayurveda?: any | null, modern?: any | null } | null, shlokas?: Array<{ __typename: 'TopicShlokas', source: string, devanagari: string, transliteration: string, meaning: string, clinicalNote?: string | null } | null> | null, dualCols?: Array<{ __typename: 'TopicDualCols', title: string, ayurvedaContent?: any | null, modernContent?: any | null } | null> | null, mnemonics?: Array<{ __typename: 'TopicMnemonics', title: string, acronym: string, expansions?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export const TopicPartsFragmentDoc = gql`
    fragment TopicParts on Topic {
  __typename
  moduleNumber
  slug
  nameAyurveda
  nameDevanagari
  nameEnglish
  paper
  semester
  units
  category
  references
  orientation {
    __typename
    why
    examWeight
  }
  definition {
    __typename
    ayurveda
    modern
  }
  shlokas {
    __typename
    source
    devanagari
    transliteration
    meaning
    clinicalNote
  }
  dualCols {
    __typename
    title
    ayurvedaContent
    modernContent
  }
  examBullets
  mnemonics {
    __typename
    title
    acronym
    expansions
  }
  body
}
    `;
export const TopicDocument = gql`
    query topic($relativePath: String!) {
  topic(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TopicParts
  }
}
    ${TopicPartsFragmentDoc}`;
export const TopicConnectionDocument = gql`
    query topicConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TopicFilter) {
  topicConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TopicParts
      }
    }
  }
}
    ${TopicPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      topic(variables: TopicQueryVariables, options?: C): Promise<{data: TopicQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicQueryVariables, query: string}> {
        return requester<{data: TopicQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicQueryVariables, query: string}, TopicQueryVariables>(TopicDocument, variables, options);
      },
    topicConnection(variables?: TopicConnectionQueryVariables, options?: C): Promise<{data: TopicConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicConnectionQueryVariables, query: string}> {
        return requester<{data: TopicConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicConnectionQueryVariables, query: string}, TopicConnectionQueryVariables>(TopicConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  